# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59691e2dc9ad7eaaf29d437064f89c2dbe9261866423c83f0dbeef17c16c1658ea84de2bd372592ea2483155e890d0290635890e354b283c9c822ccd676bb8fa


test:
  secret_key_base: 884ac7c108ee9a58559d1772ad5d57dfca82c53271f0afb53ffb376a037a5fadb7d4a2938fc6cd5d4bc561f362737dcaa3c1fe4df4220a549a2e25662c21925c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
